services:
  couchdb:
    image: couchdb:3.3
    container_name: couchdb
    restart: unless-stopped
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    volumes:
      # - couchdb-dev-data:/opt/couchdb/data
      - ./docker/couchdb/local.ini:/opt/couchdb/etc/local.d/local.ini
    networks:
      - main-network
  pgdb:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - main-network
    ports:
      - "5432:5432"
  next:
    build:
      context: .
      dockerfile: Dockerfile
    image: next
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - NEXT_PUBLIC_COUCHDB_URL=${NEXT_PUBLIC_COUCHDB_URL}
      - COUCHDB_URL=${COUCHDB_URL}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "3000:3000"
    networks:
      - main-network
    depends_on:
      - pgdb
      - couchdb

  

volumes:
  couchdb-dev-data:
    driver: local

networks:
  main-network:
    driver: bridge
